{% set provider = "google" %}
{% set goname = "github.com/terraform-providers/terraform-provider-"+provider.lower() %}
{% set version = "3.16.0" %}

{% set name = goname.split('/')[-1] %}

{% set x4_plugin = name + '_v' + version + "_x4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://{{ goname }}/archive/v{{ version }}.tar.gz
  sha256: 33b1dbdbd2d66c3a3e81462d4e3640170798b0b426ca9c13b0c75bc07d9cac5d

build:
  number: 0
  script:
    - go build -v -o {{ target_gobin }}{{ x4_plugin }}{{ target_goexe }}

requirements:
  build:
    - {{ compiler('go') }} >=1.11.3
  run:
    - terraform >=0.12,<0.13

test:
  requires:   # [win]
    - m2-bash       # [win]
    - m2-coreutils  # [win]

  commands:
    - bash -euf -c "echo 'provider \"{{ provider|lower }}\" { version=\"{{ version }}\" }' > init.tf"
    - terraform init
    # Tests that no plugins were downloaded
    - test -f .terraform/plugins/{{ goos }}_{{ goarch }}/lock.json
    - test ! -f .terraform/plugins/{{ goos }}_{{ goarch }}/{{ x4_plugin }}{{ target_goexe }}

about:
  home: https://www.terraform.io
  license: MPL-2.0
  summary: The Terraform Google provider
  doc_url: https://www.terraform.io/docs/providers/{{ provider }}/index.html
  dev_url: https://github.com/terraform-providers/{{ name }}

extra:
  recipe-maintainers:
    - conda-forge/terraform
    - agcopenhaver
    - rluria14
    - oblute
