travis:
  secure:
    BINSTAR_TOKEN: BY+ozYgbmiQd0KzaS9Hvdd/zvfAxDHgtdg4uU2hPQ9YXHsVobREUVe6nhQyK8l/22sFAIhHjqsj4Yx9hyWoAc5Q0yEyuxcIww8rnE3Grni5gd7aInYW8RZGy9qpdcHuOExZ7Hu4r/6Uo5Ic2pMAhFYssSphJ1dPG363xYeE7XCGpPGwQGrpgpyT8mx+82axDxkS7TWoRIqCrq4P5NTNr4Q747bo7qh4wHYI2a123XV4RIsmXFcNqL9/pfGooifhiyXuR6RrzKOPfBxRIMxw7Uj3tVSAlsNRGORkt5jA9O59fvN0PcD/PETgbeE8DzU4EtT02yYvdwWv+O7x9dmdDj3vJEwOXek+A8misn8/bl0LvEdRA/NAkjr6AOvFxm32LaSQDcjvKBcnwVvPxp/nPbmT0SXTLfqEK9UdBKS4Q0nBiwwjg6J//ZiwzM3lBqcLE0XIkvwEnQ5cQ1y6TmMZdch5lgLnhsXP8y9A97jpqeZNaaUm9vlb3GYHrT4gLDbQWbTJlHyV69BTZ2ynw4JDhmxQWeARBKfnnAQRgYbVA55A6/ryHYHlz36OOvpwdY6rgPHPiG3xZf0+QBDqYyWEpmBlVnaUDlboJAho1wLPLKRmxEzkRPlLOEfn7pahIvV1ACGxvCsn0ASZAp3u7gvvxQXl3kCteVnnxq1Eb7gIAzm8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
